name: Daily AI Sales Agent

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      #Checkout repo
      - uses: actions/checkout@v4

      #Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      #Install dependencies
      - run: pip install -r requirements.txt

      #Create service account file
      - run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > service_account.json
          
      #Run AI Agent
      - run: python agent.py
        env: 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}